# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8c0b75eb9afecb659be8daa9c204806683b7de6ec7fe8018074ea149ca8022df52d7a6a9af9addc679d6527c3bb336ae32742d2e496bf387aef644f409c02ee5

test:
  secret_key_base: 8c616f01fe250746044c7eb234eb0acb1ff6c3c233c0db0fc1f1f4da20a5b63d57537eea32a1087381c51cf81fa1b1972607aac8f2393c0ba8ebf939400d729f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
